### ISSUE TITLE
After the move to use repose 8.0.0.0 project doesn't compiles

### ISSUE THREAD

**Issue by maazkhan** [rackerlabs/repose-hello-world#4]
I am running "mvn install" but it fails while downloading the jar
ERROR
The following artifacts could not be resolved: org.openrepose:repose-core-api:jar:8.0.0.0, org.openrepose:utilities:jar:8.0.0.0: Failure to find org.openrepose:repose-core-api:jar:8.0.0.0 in https://maven.research.rackspacecloud.com/content/groups/aggregate was cached in the local repository, resolution will not be reattempted until the update interval of public.maven.research.rackspace.com has elapsed or updates are forced

**Comment by Mario-Lopez** [comment]
Repose 8.0.0.0 has not been released quite yet.  If you want to build against the last released Repose version, you could check out the "repose-7.3.x.x" tag.  We plan to release Repose 8 this month.  I apologize for the inconvenience.

https://github.com/rackerlabs/repose-hello-world/releases/tag/repose-7.3.x.x

**Comment by maazkhan** [comment]
@Mario-Lopez I did tried with 7.3.5.0-SNAPSHOT but looks like there are some name changes for the JAR since then.

This is what I get when using 7.3.5.0-SNAPSHOT
Failure to find org.openrepose:repose-core-api:jar:7.3.5.0-SNAPSHOT in https://maven.research.rackspacecloud.com/content/groups/aggregate was cached in the local repository, resolution will not be reattempted until the update interval of public.maven.research.rackspace.com has elapsed or updates are forced

**Comment by maazkhan** [comment]
Ok the Tag "repose-7.3.x.x" did work. Before that I was trying to change the repose version in the 8.0.x.x tag. Thanks for the help @Mario-Lopez

**Comment by Mario-Lopez** [comment]
Cool.  No problem!
